export const Sigmund = {
    name: "Sigmund",
    maneuvers: [
                   {
                       name:"Crusader's Strike",
                       spellSchool:"Devoted Spirit(Strike)",
                       level:"Crusader 1",
                       castingTime:"1 standard action",
                       range:"Melee attack",
                       target:"One creature",
                       description:"Divine energy surrounds your weapon as you strike. This power washes over you as your weapon finds its mark, mending your wounds and giving you the strength to fight on.\n\nAs part of initiating this strike, you must make a successful melee attack against an enemy whose alignment has at least one component different from yours. This foe must pose a threat to you or your allies in some direct, immediate way. If your attack hits, you or an ally within 10 feet of you heals 1d6 points of damage + 1 point per initiator level (maximum +5).",
                       maneuverExpended: false,
                   },
                   {
                       name:"Charging Minotaur",
                       spellSchool:"Stone Dragon(Strike)",
                       level:"Crusader 1",
                       castingTime:"1 full-round action",
                       range:"Melee attack",
                       target:"One creature",
                       description:"You charge at your foe, blasting him with such power that he stumbles back.\n\nAs part of this maneuver, you make a bull rush attack (PH 154) as part of a charge. Neither the movement nor the bull rush attack provokes attacks of opportunity. Resolve the bull rush attempt normally. If your Strength check exceeds the opponent's result, you deal bludgeoning damage equal to 2d6 + your Str modifier in addition to pushing the target back as normal. Assuming your Strength check is high enough, you can push your target back more than 5 feet (as normal for a bull rush, but without having to follow).",
                       maneuverExpended: false,
                   },
                   {
                       name:"Stone Bones",
                       spellSchool:"Stone Dragon",
                       level:"Crusader 1",
                       castingTime:"1 standard action",
                       range:"Personal",
                       target:"You",
                       description:"You focus your energy to enhance your defenses, drawing on the power of your weapon's impact with a foe to toughen yourself against a counterattack.\n\nWhen you use this maneuver, you make a single melee attack. If this attack hits, you gain damage reduction 5/adamantine for 1 round.",
                       maneuverExpended: false,
                   },
                   {
                       name:"Douse the Flames",
                       spellSchool:"White Raven(Strike)",
                       level:"Crusader 1",
                       castingTime:"1 standard action",
                       range:"Melee attack",
                       target:"One creature",
                       description:"You strike your enemy with a resounding blow, capturing his attention. As he turns to look, you let loose with a string of oaths, challenges, and taunts that force him to focus his attention on you.\n\nAs part of this maneuver, you make a melee attack against a single target you threaten. If your attack hits, you deal normal melee damage, and the target creature can't make attacks of opportunity for 1 round. The opponent still threatens its normal area; it simply cannot make attacks of opportunity.",
                       maneuverExpended: false,
                   },
                   {
                       name:"Vanguard Strike",
                       spellSchool:"Devoted Spirit",
                       level:"Crusader 1",
                       castingTime:"1 standard action",
                       range:"Melee attack",
                       target:"One creature",
                       description:"You batter aside your foes defenses with a vicious, overwhelming attack, leaving him vulnerable to your allies' blows.\n\nAs part of this maneuver, you make a melee attack against an opponent you threaten. If this attack hits, all your allies gain a +4 bonus on ranged and melee attacks against that target until the start of your next turn.",
                       maneuverExpended: false,
                   },
               ],
}